/**
 * @fileoverview Service for interacting with Google Gemini API.
 * Encapsulates all generative AI operations for the smart operations assistant.
 */

const { GoogleGenerativeAI } = require("@google/generative-ai");
const config = require("../config");
const stadiums = require("../data/stadiums");
const matches = require("../data/matches");
const vendors = require("../data/vendors");

// Initialize Google Generative AI client
const genAI = new GoogleGenerativeAI(config.geminiApiKey || "MOCK_API_KEY");

/**
 * Builds the context payload of the tournament data to feed into the Gemini prompt.
 * @returns {string} Formatted context string representing the current state.
 */
function getTournamentContext() {
  return `
SYSTEM CONTEXT - TOURNAMENT DATA:
- Current Local Time: 2026-07-11T12:20:00 (Tournament is currently active and group/knockout stages are in progress)
- List of 16 Host Stadiums:
${stadiums.map((s) => `  * ID: ${s.id}, Name: ${s.name}, City: ${s.city}, Country: ${s.country}, Capacity: ${s.capacity}, Coordinates: (${s.coordinates.lat}, ${s.coordinates.lng}), Features: ${s.features.join(", ")}`).join("\n")}

- Current Match Schedules & Results:
${matches.map((m) => `  * ID: ${m.id}, Stage: ${m.stage}, Group: ${m.group || "N/A"}, Teams: ${m.homeTeam} vs ${m.awayTeam}, Date: ${m.date}, Time: ${m.time}, Stadium ID: ${m.stadiumId}, Status: ${m.status}${m.score ? `, Score: ${m.score.home}-${m.score.away}` : ""}${m.attendance ? `, Attendance: ${m.attendance}` : ""}`).join("\n")}

- Live Vendor Queue & Concessions Status:
${vendors.map((v) => `  * ID: ${v.id}, Name: ${v.name}, Type: ${v.type}, Stadium ID: ${v.stadiumId}, Section: ${v.section}, Status: ${v.status}, Queue Time: ${v.queueTimeMinutes} mins, Popular Items: ${v.items.join(", ")}`).join("\n")}
`;
}

/**
 * Sends a chat query to Gemini 1.5 Flash using local database context.
 * @param {string} userMessage - The query or question from the user.
 * @param {string} [lang='en'] - Preferred language ('en', 'es', 'fr', 'pt', 'ar', 'de').
 * @returns {Promise<string>} The response generated by Gemini.
 */
async function generateOperationalResponse(userMessage, lang = "en") {
  // If the API key is missing, run in mock mode for development/testing environments without credentials
  if (!config.geminiApiKey || config.geminiApiKey === "your_gemini_api_key_here" || config.geminiApiKey === "MOCK_API_KEY") {
    console.warn("[Gemini Service] Running in MOCK MODE because GEMINI_API_KEY is not configured.");
    return mockOperationalResponse(userMessage, lang);
  }

  try {
    const model = genAI.getGenerativeModel({
      model: "gemini-1.5-flash",
      systemInstruction: `You are the Smart Stadium Operations Assistant for the FIFA World Cup 2026.
You help tournament directors, venue operations staff, security coordinators, and concession managers run operations smoothly.
Use the provided system context data (stadiums, matches, vendor status, queue times) to answer operational questions.
Be concise, actionable, and focus on stadium safety, efficiency, and visitor satisfaction.
Respond in the language specified: '${lang}' (English, Spanish, French, Portuguese, Arabic - RTL support, German).
If the query is not related to the World Cup operations, stadiums, matches, or queues, politely redirect the user back to operations.`
    });

    const context = getTournamentContext();
    const prompt = `
[User Request]
${userMessage}

[System Context Data]
${context}

Provide a precise response based on the context data in language: '${lang}'.`;

    const result = await model.generateContent(prompt);
    const response = await result.response;
    return response.text();
  } catch (error) {
    console.error("[Gemini Service] Error communicating with Gemini API:", error);
    throw new Error("Failed to generate response from operational assistant.");
  }
}

/**
 * Fallback mock response handler for testing and local runs without a valid Gemini API Key.
 * Supports all 6 requested languages.
 * @param {string} query - The query or question from the user.
 * @param {string} lang - Preferred language.
 * @returns {string} The localized mock response.
 */
function mockOperationalResponse(query, lang) {
  const normalizedQuery = query.toLowerCase();
  
  const translations = {
    en: {
      default: "I am the StadiumIQ Operations Assistant. How can I help you manage World Cup operations?",
      stadium: "The FIFA World Cup 2026 features 16 premium stadiums across Canada, Mexico, and the USA. The largest venue is Estadio Azteca in Mexico City (87,523).",
      live: "Currently, Mexico vs Canada is live at Estadio Azteca (Score: 2-1) and USA vs Japan is live at SoFi Stadium (Score: 0-0).",
      queue: "Concessions like Tacos El Capi at Estadio Azteca are currently busy with a 22-minute wait time. Texas Size BBQ at AT&T Stadium has a 25-minute wait time. Restroom Block A at MetLife Stadium has a 5-minute wait time."
    },
    es: {
      default: "Soy el Asistente de Operaciones de StadiumIQ. ¿Cómo puedo ayudarle a gestionar las operaciones del Mundial?",
      stadium: "La Copa Mundial de la FIFA 2026 cuenta con 16 estadios en Canadá, México y EE. UU. El más grande es el Estadio Azteca en la Ciudad de México (87,523).",
      live: "Actualmente, México vs Canadá está en vivo en el Estadio Azteca (Marcador: 2-1) y EE. UU. vs Japón en el SoFi Stadium (Marcador: 0-0).",
      queue: "Tacos El Capi en el Estadio Azteca está ocupado con 22 minutos de espera. Texas Size BBQ en el AT&T Stadium tiene 25 minutos de espera."
    },
    fr: {
      default: "Je suis l'assistant des opérations de StadiumIQ. Comment puis-je vous aider à gérer les opérations de la Coupe du Monde ?",
      stadium: "La Coupe du Monde de la FIFA 2026 comprend 16 stades au Canada, au Mexique et aux États-Unis. Le plus grand est l'Estadio Azteca à Mexico (87 523).",
      live: "Actuellement, Mexique vs Canada est en direct à l'Estadio Azteca (Score: 2-1) et USA vs Japon est en direct au SoFi Stadium (Score: 0-0).",
      queue: "Les files d'attente aux Tacos El Capi à l'Estadio Azteca sont d'environ 22 minutes. Le Texas Size BBQ à l'AT&T Stadium a 25 minutes d'attente."
    },
    pt: {
      default: "Sou o Assistente de Operações do StadiumIQ. Como posso ajudar a gerenciar as operações da Copa do Mundo?",
      stadium: "A Copa do Mundo FIFA 2026 apresenta 16 estádios no Canadá, México e EUA. O maior é o Estádio Azteca na Cidade do México (87.523).",
      live: "Atualmente, México vs Canadá está ao vivo no Estádio Azteca (Placar: 2-1) e EUA vs Japão está ao vivo no SoFi Stadium (Placar: 0-0).",
      queue: "Tacos El Capi no Estádio Azteca está movimentado com 22 minutos de espera. Texas Size BBQ no AT&T Stadium tem 25 minutos de espera."
    },
    ar: {
      default: "أنا مساعد عمليات StadiumIQ. كيف يمكنني مساعدتك في إدارة عمليات كأس العالم؟",
      stadium: "تضم بطولة كأس العالم لكرة القدم ٢٠٢٦ ١٦ ملعباً متميزاً في كندا والمكسيك والولايات المتحدة. أكبر الملاعب هو ملعب أزتيكا في مدينة مكسيكو (٨٧,٥٢٣).",
      live: "حالياً، مباراة المكسيك ضد كندا مباشرة في ملعب أزتيكا (النتيجة: ٢-١) والولايات المتحدة ضد اليابان مباشرة في ملعب سوفي (النتيجة: ٠-٠).",
      queue: "مأكولات 'تاكوس إل كابي' في ملعب أزتيكا مزدحمة حالياً بوقت انتظار ٢٢ دقيقة. شواء 'تكساس سايز' في ملعب إيه تي أند تي لديه وقت انتظار ٢٥ دقيقة."
    },
    de: {
      default: "Ich bin der StadiumIQ Operations-Assistent. Wie kann ich Ihnen bei der Verwaltung des WM-Betriebs helfen?",
      stadium: "Die FIFA Fussball-Weltmeisterschaft 2026 umfasst 16 Stadien in Kanada, Mexiko und den USA. Der größte Austragungsort ist das Aztekenstadion in Mexiko-Stadt (87.523).",
      live: "Aktuell läuft Mexiko gegen Kanada live im Aztekenstadion (Spielstand: 2-1) und USA gegen Japan live im SoFi Stadium (Spielstand: 0-0).",
      queue: "Concessions wie Tacos El Capi im Aztekenstadion haben derzeit eine Wartezeit von 22 Minuten. Texas Size BBQ im AT&T Stadium hat 25 Minuten Wartezeit."
    }
  };

  const text = translations[lang] || translations.en;

  if (normalizedQuery.includes("stadium") || normalizedQuery.includes("venue") || normalizedQuery.includes("estadio") || normalizedQuery.includes("stade") || normalizedQuery.includes("ملعب")) {
    return text.stadium;
  }
  if (normalizedQuery.includes("live") || normalizedQuery.includes("match") || normalizedQuery.includes("partido") || normalizedQuery.includes("direct") || normalizedQuery.includes("مباراة") || normalizedQuery.includes("spiel")) {
    return text.live;
  }
  if (normalizedQuery.includes("queue") || normalizedQuery.includes("wait") || normalizedQuery.includes("line") || normalizedQuery.includes("vendor") || normalizedQuery.includes("cola") || normalizedQuery.includes("attente") || normalizedQuery.includes("انتظار") || normalizedQuery.includes("warten")) {
    return text.queue;
  }
  
  return text.default;
}

module.exports = {
  generateOperationalResponse
};
